<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shortage Report — PO #{{ $po->po_number }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 12px; color: #222; }
        .header { background-color: #dc3545; color: #fff; padding: 18px 24px; }
        .header h1 { font-size: 18px; margin-bottom: 4px; }
        .header p { font-size: 12px; opacity: 0.9; }
        .content { padding: 20px 24px; }
        table.meta { width: 100%; margin-bottom: 16px; }
        table.meta td { padding: 4px 0; }
        table.meta td:first-child { color: #666; width: 160px; }
        table.meta td:last-child { font-weight: bold; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.items th { background: #dc3545; color: #fff; padding: 6px 8px; text-align: left; font-size: 11px; }
        table.items td { padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px; }
        table.items tr:nth-child(even) td { background: #f9f9f9; }
        .total-row td { font-weight: bold; border-top: 2px solid #dc3545; }
        .footer { margin-top: 20px; font-size: 10px; color: #888; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Shortage Report — PO #{{ $po->po_number }}</h1>
        <p>Vendor: {{ $po->vendor->name ?? 'N/A' }}</p>
    </div>

    <div class="content">
        <table class="meta">
            <tr>
                <td>PO Number:</td>
                <td>{{ $po->po_number }}</td>
            </tr>
            <tr>
                <td>Vendor:</td>
                <td>{{ $po->vendor->name ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>PO Status:</td>
                <td>{{ strtoupper($po->status) }}</td>
            </tr>
        </table>

        <table class="items">
            <thead>
                <tr>
                    <th>Product</th>
                    <th style="text-align: right;">Requested Qty</th>
                    <th style="text-align: right;">Received Qty</th>
                    <th style="text-align: right;">Shortage Qty</th>
                    <th style="text-align: right;">Unit Cost</th>
                    <th style="text-align: right;">Cost Impact</th>
                </tr>
            </thead>
            <tbody>
                @php $totalImpact = 0; @endphp
                @foreach ($shortageItems as $item)
                    @php
                        $shortQty = $item->requested_quantity - $item->received_quantity;
                        $impact = $shortQty * $item->unit_cost;
                        $totalImpact += $impact;
                    @endphp
                    <tr>
                        <td>{{ $item->product->product_name ?? 'N/A' }}</td>
                        <td style="text-align: right;">{{ $item->requested_quantity }}</td>
                        <td style="text-align: right;">{{ $item->received_quantity }}</td>
                        <td style="text-align: right;">{{ $shortQty }}</td>
                        <td style="text-align: right;">${{ number_format($item->unit_cost, 2) }}</td>
                        <td style="text-align: right;">${{ number_format($impact, 2) }}</td>
                    </tr>
                @endforeach
                <tr class="total-row">
                    <td colspan="5" style="text-align: right;">Total Shortage Value:</td>
                    <td style="text-align: right;">${{ number_format($totalImpact, 2) }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by the Warehouse Management System on {{ now()->timezone(config('app.display_timezone'))->format('d M Y, h:i A') }}
    </div>
</body>
</html>
