<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store Order #{{ $storeOrder->po_number }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 12px; color: #222; }
        .header { background-color: #1a73e8; color: #fff; padding: 18px 24px; }
        .header h1 { font-size: 18px; margin-bottom: 4px; }
        .header p { font-size: 12px; opacity: 0.9; }
        .content { padding: 20px 24px; }
        table.meta { width: 100%; margin-bottom: 16px; }
        table.meta td { padding: 4px 0; }
        table.meta td:first-child { color: #666; width: 160px; }
        table.meta td:last-child { font-weight: bold; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.items th { background: #1a73e8; color: #fff; padding: 6px 8px; text-align: left; font-size: 11px; }
        table.items td { padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px; }
        table.items tr:nth-child(even) td { background: #f9f9f9; }
        .footer { margin-top: 20px; font-size: 10px; color: #888; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Store Order — #{{ $storeOrder->po_number }}</h1>
        <p>{{ $storeOrder->store->store_name ?? 'N/A' }}</p>
    </div>

    <div class="content">
        <table class="meta">
            <tr>
                <td>Store:</td>
                <td>{{ $storeOrder->store->store_name ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>Request Date:</td>
                <td>{{ optional($storeOrder->request_date)->format('d M Y') }}</td>
            </tr>
            <tr>
                <td>Status:</td>
                <td>{{ strtoupper($storeOrder->status) }}</td>
            </tr>
            <tr>
                <td>Note:</td>
                <td>{{ $storeOrder->admin_note ?? '—' }}</td>
            </tr>
        </table>

        <table class="items">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Product</th>
                    <th>Barcode</th>
                    <th style="text-align: right;">Requested Qty</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($storeOrder->items as $i => $item)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $item->product->product_name ?? 'N/A' }}</td>
                    <td>{{ $item->product->barcode ?? 'N/A' }}</td>
                    <td style="text-align: right;">{{ $item->requested_qty }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by the Warehouse Management System on {{ now()->timezone(config('app.display_timezone'))->format('d M Y, h:i A') }}
    </div>
</body>
</html>
